language: go

go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3

before_install:
  - git clone https://github.com/Softmotions/ejdb.git
  - cd ejdb/tcejdb
  - ./configure
  - make
  - sudo make install
  - cd ../..
